VFDCFM ;DSS/SGM - BRIEF DOCS FOR VFDCFM ENTRY POINTS ;01/14/2005 13:26
 ;;2009.2;DSS,INC VXVISTA OPEN SOURCE;;01 Dec 2009
 ;Copyright 1995-2009,Document Storage Systems Inc. All Rights Reserved
 ;
OUT Q:$G(FUN) VFDC Q
 ;
 ;--------------------  VFDCFM01  --------------------
MSG(FLGS,OUT,WIDTH,LEFT,INPUT) ;
 G M^VFDCFM01
 ;
 ;--------------------  VFDCFM05  --------------------
FIND(VFDC,INPUT) ; RPC: VFDC FM FIND
 D FIND^VFDCFM05(.VFDC,.INPUT) Q
 ;
LIST(VFDC,INPUT) ; RPC: VFDC FM LIST
 D LIST^VFDCFM05(.VFDC,.INPUT) Q
 ;
 ;--------------------  VFDCFM06  --------------------
EXTERNAL(VFDC,FILE,FIELD,VALUE,FUN) ; rpc: VFDC FM EXTERNAL
 D INIT("FILE^FIELD^VALUE^FUN") D
 .N FUN D EXTERNAL^VFDCFM06(.VFDC,FILE,FIELD,VALUE)
 .Q
 G OUT
 ;
FIELD(VFDC,FILE,FIELD,FLAG,ATT,TYPE) ; rpc: VFDC FM GET FIELD ATTRIB
 D INIT("FIELD^FILE^FLAG^TYPE")
 D FIELD^VFDCFM06(.VFDC,FILE,FIELD,FLAG,.ATT,TYPE)
 Q
 ;
FIELDLST(VFDC,INPUT) ;
 D FIELDLST^VFDCFM06(.VFDC,.INPUT)
 Q
 ;
ROOT(VFDC,FILE,IENS,FLAG,FUN) ;
 D INIT("FILE^IENS^FLAG^FUN") D
 .N FUN D ROOT^VFDCFM06(.VFDC,FILE,IENS,FLAG)
 .Q
 G OUT
 ;
VFILE(VFDC,FILE,FUN) ; rpc: VFDC FM VERIFY FILE
 D INIT("FILE^FUN") D
 .N FUN D VFILE^VFDCFM06(.VFDC,FILE)
 .Q
 G OUT
 ;
VFIELD(VFDC,FILE,FIELD,FUN) ; rpc: VFDC FM VERIFY FIELD
 D INIT("FIELD^FIELD^FUN") D
 .N FUN D VFIELD^VFDCFM06(.VFDC,FILE,FIELD)
 .Q
 G OUT
 ;
VIENS(VFDC,IENS,FUN) ;
 D INIT("IENS^FUN") D
 .N FUN D VIENS^VFDCFM06(.VFDC,IENS)
 .Q
 G OUT
 ;
 ;---------------  subroutines  --------------------
INIT(STR) ; list of variable names to initialize
 N I,X
 F I=1:1:$L(STR,U) S X=$P(STR,U,I) I X'="" S @X=$G(@X)
 Q
